export const data = [
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "Abul Kalam",
    description: "Lorem ipsum dolor sit amet con...",
    rating: '1 / 2',
    chat: 15,
    attach: 25,
    date: "30-12-2022",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "Jane Doe",
    description: "Ut enim ad minim veniam...",
    rating: '3 / 5',
    chat: 12,
    attach: 20,
    date: "15-06-2023",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "John Smith",
    description: "Duis aute irure dolor in...",
    rating: '4 / 5',
    chat: 8,
    attach: 18,
    date: "05-04-2023",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "Emily Johnson",
    description: "Excepteur sint occaecat cupidatat...",
    rating: '5 / 5',
    chat: 20,
    attach: 30,
    date: "22-08-2023",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "Michael Brown",
    description: "Lorem ipsum dolor sit amet con...",
    rating: '2 / 5',
    chat: 10,
    attach: 15,
    date: "10-01-2023",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "Sarah Williams",
    description: "Ut enim ad minim veniam...",
    rating: '4 / 5',
    chat: 18,
    attach: 28,
    date: "03-11-2022",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "Robert Davis",
    description: "Duis aute irure dolor in...",
    rating: '3 / 5',
    chat: 14,
    attach: 22,
    date: "17-07-2023",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "Linda Martinez",
    description: "Excepteur sint occaecat cupidatat...",
    rating: '5 / 5',
    chat: 25,
    attach: 35,
    date: "08-09-2022",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "William Wilson",
    description: "Lorem ipsum dolor sit amet con...",
    rating: '3 / 5',
    chat: 12,
    attach: 20,
    date: "21-03-2023",
  },
  {
    img1: "/public/images/avatarF.jpg",
    img2: "/public/images/avatarM.png",
    clientName: "Amanda Brown",
    description: "Ut enim ad minim veniam...",
    rating: '4 / 5',
    chat: 16,
    attach: 26,
    date: "12-12-2022",
  },
];
